"""
Falsification tests for claim: "ready to merge to development — no dangers"
Generated by /falsify audit on 2026-04-27, converted to GREEN after fixes.
"""

import pytest
from unittest.mock import MagicMock
from views_r2darts2.engines.darts_forecaster import DartsForecaster
from views_r2darts2.transformers.views_dataset_darts import _ViewsDatasetDarts
from views_r2darts2.catalogs.model_catalog import ModelCatalog


@pytest.fixture
def nbeats_config():
    return {
        "run_type": "test",
        "num_samples": 1,
        "mc_dropout": False,
        "algorithm": "NBEATSModel",
        "targets": ["target"],
        "steps": list(range(1, 37)),
        "input_chunk_length": 24,
        "output_chunk_length": 36,
        "output_chunk_shift": 0,
        "num_stacks": 2,
        "num_blocks": 3,
        "num_layers": 3,
        "layer_widths": 64,
        "activation": "LeakyReLU",
        "expansion_coefficient_dim": 5,
        "trend_polynomial_degree": 2,
        "generic_architecture": True,
        "dropout": 0.3,
        "batch_size": 8,
        "n_epochs": 1,
        "lr": 0.0003,
        "weight_decay": 0.0003,
        "loss_function": "WeightedPenaltyHuberLoss",
        "optimizer_cls": "Adam",
        "delta": 0.025,
        "zero_threshold": 0.01,
        "non_zero_weight": 7.0,
        "false_positive_weight": 1.0,
        "false_negative_weight": 10.0,
        "lr_scheduler_factor": 0.5,
        "lr_scheduler_patience": 5,
        "lr_scheduler_cls": "ReduceLROnPlateau",
        "lr_scheduler_min_lr": 1e-6,
        "early_stopping_patience": 5,
        "early_stopping_min_delta": 0.001,
        "gradient_clip_val": 1.0,
        "force_reset": True,
        "random_state": 1,
        "name": "TestModel",
        "use_static_covariates": True,
        "use_reversible_instance_norm": False,
    }


def test_predict_before_train_raises_runtime_error(nbeats_config):
    """CIC §6: predict() must raise RuntimeError when scalers are not fitted."""
    dataset = MagicMock(spec=_ViewsDatasetDarts)
    dataset.features = ["feat_a"]
    dataset.targets = ["target"]

    model = ModelCatalog(config=nbeats_config).get_model("NBEATSModel")

    forecaster = DartsForecaster(
        dataset=dataset,
        model=model,
        partition_dict={"train": (0, 100), "test": (100, 120)},
        target_scaler="MinMaxScaler",
        feature_scaler="StandardScaler",
        random_state=42,
    )

    assert forecaster.scaler_fitted is False
    with pytest.raises(RuntimeError, match="predict.*called before scalers were fitted"):
        forecaster.predict(sequence_number=0)


def test_predict_without_scaler_does_not_raise(nbeats_config):
    """When no target_scaler is configured, predict() should not guard on unfitted state."""
    dataset = MagicMock(spec=_ViewsDatasetDarts)
    dataset.features = ["feat_a"]
    dataset.targets = ["target"]

    model = ModelCatalog(config=nbeats_config).get_model("NBEATSModel")

    forecaster = DartsForecaster(
        dataset=dataset,
        model=model,
        partition_dict={"train": (0, 100), "test": (100, 120)},
        random_state=42,
    )

    assert forecaster.target_scaler is None
    assert forecaster.scaler_fitted is False
